apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: demo
  source:
    path   : "."
    repoURL: "git@github.com:sbodnia/sample-html-website.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: demo
        value: creeger/htmlapp

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         
